"""empty message

Revision ID: 5f2b99d80aff
Revises: 3cf5eb9e91c3
Create Date: 2025-04-29 13:52:53.312350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f2b99d80aff'
down_revision = '3cf5eb9e91c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tbl_categories', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
